/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SimplePostModel } from '../../models/simple-post-model';

export interface GetAllPostsByTag$Json$Params {
  id: string;
}

export function getAllPostsByTag$Json(http: HttpClient, rootUrl: string, params: GetAllPostsByTag$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SimplePostModel>>> {
  const rb = new RequestBuilder(rootUrl, getAllPostsByTag$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SimplePostModel>>;
    })
  );
}

getAllPostsByTag$Json.PATH = '/api/v1/Post/GetPostsByTag/{id}/tag';
