/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PostModel } from '../../models/post-model';

export interface GetAllPosts$Plain$Params {
}

export function getAllPosts$Plain(http: HttpClient, rootUrl: string, params?: GetAllPosts$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PostModel>>> {
  const rb = new RequestBuilder(rootUrl, getAllPosts$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PostModel>>;
    })
  );
}

getAllPosts$Plain.PATH = '/api/forum/v1/Post/GetPosts';
