/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SimplePostModel } from '../../models/simple-post-model';

export interface GetAllPostsByCategory$Json$Params {
  id: string;
}

export function getAllPostsByCategory$Json(http: HttpClient, rootUrl: string, params: GetAllPostsByCategory$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SimplePostModel>>> {
  const rb = new RequestBuilder(rootUrl, getAllPostsByCategory$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SimplePostModel>>;
    })
  );
}

getAllPostsByCategory$Json.PATH = '/api/forum/v1/Post/GetPostsByCategory/{id}/category';
