/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PostModel } from '../../models/post-model';

export interface GetPostById$Plain$Params {
  id: string;
}

export function getPostById$Plain(http: HttpClient, rootUrl: string, params: GetPostById$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<PostModel>> {
  const rb = new RequestBuilder(rootUrl, getPostById$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PostModel>;
    })
  );
}

getPostById$Plain.PATH = '/api/forum/v1/Post/GetPostById/{id}';
