/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OperationResultDto } from '../../models/operation-result-dto';

export interface BlockUser$Json$Params {
  id: string;
  minutes?: number;
}

export function blockUser$Json(http: HttpClient, rootUrl: string, params: BlockUser$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<OperationResultDto>> {
  const rb = new RequestBuilder(rootUrl, blockUser$Json.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('minutes', params.minutes, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OperationResultDto>;
    })
  );
}

blockUser$Json.PATH = '/api/identity/Users/{id}/block';
