/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateUserCommand } from '../../models/create-user-command';
import { CreateUserResultDto } from '../../models/create-user-result-dto';

export interface CreateUser$Plain$Params {
      body?: CreateUserCommand
}

export function createUser$Plain(http: HttpClient, rootUrl: string, params?: CreateUser$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CreateUserResultDto>> {
  const rb = new RequestBuilder(rootUrl, createUser$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreateUserResultDto>;
    })
  );
}

createUser$Plain.PATH = '/api/identity/Users';
