/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedUsersDto } from '../../models/paged-users-dto';

export interface GetPagedUsers$Json$Params {
  pageIndex?: number;
  pageSize?: number;
}

export function getPagedUsers$Json(http: HttpClient, rootUrl: string, params?: GetPagedUsers$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedUsersDto>> {
  const rb = new RequestBuilder(rootUrl, getPagedUsers$Json.PATH, 'get');
  if (params) {
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedUsersDto>;
    })
  );
}

getPagedUsers$Json.PATH = '/api/identity/Users/paged';
