/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OperationResultDto } from '../../models/operation-result-dto';

export interface UnblockUser$Plain$Params {
  id: string;
}

export function unblockUser$Plain(http: HttpClient, rootUrl: string, params: UnblockUser$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<OperationResultDto>> {
  const rb = new RequestBuilder(rootUrl, unblockUser$Plain.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OperationResultDto>;
    })
  );
}

unblockUser$Plain.PATH = '/api/identity/Users/{id}/unblock';
