/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeleteTagCommand } from '../../models/delete-tag-command';
import { Unit } from '../../models/unit';

export interface DeleteTag$Plain$Params {
      body?: DeleteTagCommand
}

export function deleteTag$Plain(http: HttpClient, rootUrl: string, params?: DeleteTag$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Unit>> {
  const rb = new RequestBuilder(rootUrl, deleteTag$Plain.PATH, 'delete');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Unit>;
    })
  );
}

deleteTag$Plain.PATH = '/api/forum/v1/Tag/DeleteTag';
