/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TagModel } from '../../models/tag-model';

export interface GetAllTags$Plain$Params {
}

export function getAllTags$Plain(http: HttpClient, rootUrl: string, params?: GetAllTags$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TagModel>>> {
  const rb = new RequestBuilder(rootUrl, getAllTags$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TagModel>>;
    })
  );
}

getAllTags$Plain.PATH = '/api/forum/v1/Tag/GetTags';
