/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TagModel } from '../../models/tag-model';

export interface GetTagById$Plain$Params {
  id: string;
}

export function getTagById$Plain(http: HttpClient, rootUrl: string, params: GetTagById$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TagModel>> {
  const rb = new RequestBuilder(rootUrl, getTagById$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TagModel>;
    })
  );
}

getTagById$Plain.PATH = '/api/v1/Tag/GetTag/{id}';
