/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TagModel } from '../../models/tag-model';

export interface GetAllTags$Json$Params {
}

export function getAllTags$Json(http: HttpClient, rootUrl: string, params?: GetAllTags$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TagModel>>> {
  const rb = new RequestBuilder(rootUrl, getAllTags$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TagModel>>;
    })
  );
}

getAllTags$Json.PATH = '/api/v1/Tag/GetTags';
