/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LoginCommand } from '../../models/login-command';
import { LoginResultDto } from '../../models/login-result-dto';

export interface LoginUser$Json$Params {
      body?: LoginCommand
}

export function loginUser$Json(http: HttpClient, rootUrl: string, params?: LoginUser$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<LoginResultDto>> {
  const rb = new RequestBuilder(rootUrl, loginUser$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LoginResultDto>;
    })
  );
}

loginUser$Json.PATH = '/api/identity/v1/Auth/login';
