/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OperationResultDto } from '../../models/operation-result-dto';
import { RegisterUserCommand } from '../../models/register-user-command';

export interface RegisterUser$Json$Params {
      body?: RegisterUserCommand
}

export function registerUser$Json(http: HttpClient, rootUrl: string, params?: RegisterUser$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<OperationResultDto>> {
  const rb = new RequestBuilder(rootUrl, registerUser$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OperationResultDto>;
    })
  );
}

registerUser$Json.PATH = '/api/identity/v1/Auth/register';
