/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateCategoryCommand } from '../../models/create-category-command';
import { Unit } from '../../models/unit';

export interface CreateCategory$Json$Params {
      body?: CreateCategoryCommand
}

export function createCategory$Json(http: HttpClient, rootUrl: string, params?: CreateCategory$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Unit>> {
  const rb = new RequestBuilder(rootUrl, createCategory$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Unit>;
    })
  );
}

createCategory$Json.PATH = '/api/forum/v1/Category/CreateCategory';
