/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryModel } from '../../models/category-model';

export interface GetCategoryById$Json$Params {
  id: string;
}

export function getCategoryById$Json(http: HttpClient, rootUrl: string, params: GetCategoryById$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryModel>> {
  const rb = new RequestBuilder(rootUrl, getCategoryById$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoryModel>;
    })
  );
}

getCategoryById$Json.PATH = '/api/forum/v1/Category/GetCategory/{id}';
