/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateRoleCommand } from '../../models/create-role-command';
import { CreateRoleResultDto } from '../../models/create-role-result-dto';

export interface CreateRole$Json$Params {
      body?: CreateRoleCommand
}

export function createRole$Json(http: HttpClient, rootUrl: string, params?: CreateRole$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CreateRoleResultDto>> {
  const rb = new RequestBuilder(rootUrl, createRole$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreateRoleResultDto>;
    })
  );
}

createRole$Json.PATH = '/api/identity/Roles';
