/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateRoleCommand } from '../../models/update-role-command';
import { UpdateRoleResultDto } from '../../models/update-role-result-dto';

export interface UpdateRole$Plain$Params {
  id: string;
      body?: UpdateRoleCommand
}

export function updateRole$Plain(http: HttpClient, rootUrl: string, params: UpdateRole$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UpdateRoleResultDto>> {
  const rb = new RequestBuilder(rootUrl, updateRole$Plain.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UpdateRoleResultDto>;
    })
  );
}

updateRole$Plain.PATH = '/api/identity/Roles/{id}';
