/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommentModel } from '../../models/comment-model';

export interface GetCommentById$Plain$Params {
  id: string;
}

export function getCommentById$Plain(http: HttpClient, rootUrl: string, params: GetCommentById$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentModel>> {
  const rb = new RequestBuilder(rootUrl, getCommentById$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommentModel>;
    })
  );
}

getCommentById$Plain.PATH = '/api/forum/v1/Comment/GetCommentById/{id}';
