/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommentModel } from '../../models/comment-model';

export interface GetAllCommentsByPost$Json$Params {
  postId: string;
}

export function getAllCommentsByPost$Json(http: HttpClient, rootUrl: string, params: GetAllCommentsByPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CommentModel>>> {
  const rb = new RequestBuilder(rootUrl, getAllCommentsByPost$Json.PATH, 'get');
  if (params) {
    rb.path('postId', params.postId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CommentModel>>;
    })
  );
}

getAllCommentsByPost$Json.PATH = '/api/forum/v1/Comment/GetCommentsByPost/{postId}/post';
