/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AddTagToPostCommand } from './models/add-tag-to-post-command';
export type { CategoryModel } from './models/category-model';
export type { CreateCategoryCommand } from './models/create-category-command';
export type { CreatePostCommand } from './models/create-post-command';
export type { CreateRoleCommand } from './models/create-role-command';
export type { CreateRoleResultDto } from './models/create-role-result-dto';
export type { CreateTagCommand } from './models/create-tag-command';
export type { CreateUserCommand } from './models/create-user-command';
export type { CreateUserResultDto } from './models/create-user-result-dto';
export type { CurrentUserDto } from './models/current-user-dto';
export type { DeleteCategoryCommand } from './models/delete-category-command';
export type { DeletePostCommand } from './models/delete-post-command';
export type { DeleteTagCommand } from './models/delete-tag-command';
export type { GetCurrentUserResultDto } from './models/get-current-user-result-dto';
export type { LoginCommand } from './models/login-command';
export type { LoginResultDto } from './models/login-result-dto';
export type { OperationResultDto } from './models/operation-result-dto';
export type { PagedUsersDto } from './models/paged-users-dto';
export type { PostModel } from './models/post-model';
export type { RegisterUserCommand } from './models/register-user-command';
export type { RemoveTagFromPostCommand } from './models/remove-tag-from-post-command';
export type { RoleDto } from './models/role-dto';
export type { SimplePostModel } from './models/simple-post-model';
export type { TagModel } from './models/tag-model';
export type { Unit } from './models/unit';
export type { UpdateRoleCommand } from './models/update-role-command';
export type { UpdateRoleResultDto } from './models/update-role-result-dto';
export type { UpdateUserCommand } from './models/update-user-command';
export type { UpdateUserResultDto } from './models/update-user-result-dto';
export type { UserDto } from './models/user-dto';
