/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommentModel {
  authorId?: string;
  content?: string | null;
  createdAt?: string;
  id?: string;
  postId?: string;
  updatedAt?: string;
}
