/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePostCommand {
  categoryName: string;
  content: string;
  tagNames?: Array<string> | null;
  title: string;
}
