/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDto } from '../models/user-dto';
export interface PagedUsersDto {
  pageIndex?: number;
  pageSize?: number;
  totalCount?: number;
  users?: Array<UserDto> | null;
}
