/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterUserCommand {
  email?: string | null;
  password?: string | null;
  roles?: Array<string> | null;
  userName?: string | null;
}
