/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdatePostCommand {
  authorId?: string | null;
  categoryName?: string | null;
  content?: string | null;
  id: string;
  isPublished?: boolean | null;
  title?: string | null;
}
