/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCommentCommand {
  authorId?: string | null;
  content?: string | null;
  id: string;
  postId?: string | null;
}
