/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  accessFailedCount?: number;
  active?: boolean;
  email?: string | null;
  id?: string;
  roles?: Array<string> | null;
  userName?: string | null;
}
